spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false

server:
  port: 80

api:
  endpoint:
    base-url: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
